# Generated by Django 3.0.6 on 2021-01-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(db_index=True),
        ),
    ]
