# Generated by Django 3.1.5 on 2021-01-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210121_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_pub']},
        ),
    ]
